<?php

namespace Gesty\GestyBundle\Entity;

/**
 * FoyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FoyerRepository extends \Doctrine\ORM\EntityRepository
{
}
