<?php
/**
 * Created by PhpStorm.
 * User: Mikou
 * Date: 16/11/2015
 * Time: 23:29
 */


namespace Gesty\GestyBundle\Entity;

/**
 * FoyerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
}