<?php

namespace WCS\CantineBundle\Entity;

/**
 * archiveStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class archiveStatRepository extends \Doctrine\ORM\EntityRepository
{
}
