<?php

namespace WCS\CantineBundle\Entity;

/**
 * ArchiveStatRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchiveStatRepository extends \Doctrine\ORM\EntityRepository
{
}
