<?php

namespace WCS\CantineBundle\Entity;

/**
 * FeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriesRepository extends \Doctrine\ORM\EntityRepository
{
    public function findListDateTimes($annee)
    {
        $feries = $this->findBy(array('annee' => $annee));

        $feriesArray = [];
        if (is_array($feries) && count($feries)) {
            $feriesArray[] = $feries[0]->getPaques();
            $feriesArray[] = $feries[0]->getPentecote();
            $feriesArray[] = $feries[0]->getAscension();
            $feriesArray[] = $feries[0]->getVendrediAscension();
        }

        return $feriesArray;
    }
}
