<?php

namespace WCS\CantineBundle\Entity;

/**
 * FeriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FeriesRepository extends \Doctrine\ORM\EntityRepository
{
}
