<?php

namespace WCS\CantineBundle\Entity;

/**
 * GarderieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarderieRepository extends \Doctrine\ORM\EntityRepository
{
}
