<?php

namespace WCS\CantineBundle\Entity;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * GarderieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GarderieRepository extends ActivityRepositoryAbstract
{
    public function count()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    protected function configureDayListOptions(OptionsResolver $resolver)
    {
        $resolver->setRequired(array('is_morning'));
    }

    /**
     * @param array $options at least the key "is_morning" must be defined
     * @return array
     */
    public function getDayList($options)
    {
        $school = $options['school'];

        $day    = $options['date_day']->format('Y-m-d');
        if ($options['is_morning']) {
            $day = $day . " 08:00";
        }
        else {
            $day = $day . " 17:00";
        }

        // Request pupils to the database from a certain date
        return $this->getEntityManager()
            ->createQuery(
                'SELECT g FROM WCSCantineBundle:Garderie g 
                 JOIN g.eleve e 
                 JOIN e.division d 
                 WHERE g.date_heure LIKE :day 
                    AND d.school = :school
                 ORDER BY e.nom'
            )
            ->setParameter(':day', "%".$day."%")
            ->setParameter(':school', $school)
            ->getResult();
    }
}
