<?php

namespace WCS\CantineBundle\Entity;

/**
 * LunchRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LunchRepository extends \Doctrine\ORM\EntityRepository
{
}
