<?php

namespace WCS\CantineBundle\Entity;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends \Doctrine\ORM\EntityRepository
{
}
