<?php

namespace WCS\CantineBundle\Entity;
use Scheduler\Component\DateContainer\Period;

/**
 * SchoolYearRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SchoolYearRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param \DateTimeInterface $date
     * @return null|Period
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function getSchoolYearIncluding(\DateTimeInterface $date)
    {
        $result = $this->getEntityManager()->createQuery('
            SELECT s
            FROM WCSCantineBundle:SchoolYear s 
            WHERE DATE(s.dateStart) < :date_day
            AND DATE(s.dateEnd) > :date_day
        ')
            ->setParameter(':date_day', $date->format('Y-m-d'))
            ->getOneOrNullResult();

        if ($result) {
            return new Period($result->getDateStart(), $result->getDateEnd());
        }

        return null;
    }
}
