<?php

namespace WCS\CantineBundle\Entity;

/**
 * TapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapRepository extends ActivityRepositoryAbstract
{
    public function count()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param \WCS\CantineBundle\Entity\School $school
     * @return array
     */
    public function getDayList($options)
    {
        $school = $options['school'];
        $day    = $options['date_day']->format('Y-m-d');

        $query = $this
            ->createQueryBuilder('t')
            ->join('t.eleve', 'e')
            ->join('e.division', 'd')
            ->where('DATE(t.date) = :day')
            ->andWhere('d.school = :place')
            ->orderBy('d.grade')
            ->addOrderBy('d.headTeacher')
            ->addOrderBy('e.nom')
            ->setParameter(':day', $day)
            ->setParameter(':place', $school);

        $query = $this->excludePupilsTravellingAt($query, 'e', $options['date_day']);

        return $query->getQuery()->getResult();
    }

}
