<?php

namespace WCS\CantineBundle\Entity;

/**
 * TapRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TapRepository extends ActivityRepositoryAbstract
{
    public function count()
    {
        return $this->createQueryBuilder('a')
            ->select('COUNT(a)')
            ->getQuery()
            ->getSingleScalarResult();
    }

    /**
     * @param \WCS\CantineBundle\Entity\School $school
     * @return array
     */
    public function getTodayList(School $school, $options)
    {
        // Format the date
        $date = new \DateTime();
        $now = $date->format('Y-m-d');

        // Request pupils to the database from a certain date
        return $this->getEntityManager()
            ->createQuery(
                'SELECT t FROM WCSCantineBundle:Tap t 
                 JOIN t.eleve e 
                 JOIN e.division d 
                 WHERE t.date LIKE :now 
                    AND d.school = :school
                 ORDER BY e.nom'
            )
            ->setParameter(':now', "%".$now."%")
            ->setParameter(':school', $school)
            ->getResult();
    }

}
