<?php

namespace WCS\CantineBundle\Entity;

/**
 * VoyageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoyageRepository extends \Doctrine\ORM\EntityRepository
{
    public function findByDivisionsAnneeScolaire($params)
    {
        $division = $params["division"];

        // récupère la date du jour
        $date = new \DateTime();
        $now = $date->format('Y-m-d');

        return $this->getEntityManager()
            ->createQuery(
                'SELECT v FROM WCSCantineBundle:Voyage v 
                 JOIN v.divisions d 
                 WHERE v.estAnnule = FALSE 
                 AND d = :division 
                 ORDER BY v.date_debut'
            )
            ->setParameter(':division', $division)
//            ->setParameter(':now', $now)
            ->getResult();

    }
}
