<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;


/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/bundles/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    const TYPE_DOMICILE     = 1;
    const TYPE_PRESTATIONS  = 2;
    const TYPE_SALAIRE1     = 3;
    const TYPE_SALAIRE2     = 4;
    const TYPE_SALAIRE3     = 5;
    const TYPE_IMPOTS       = 6;

    public function setEmail($email){
        parent::setEmail($email);
        parent::setUsername($email);
    }

    public function __construct($id=null)
    {
        parent::__construct();
        $this->enabled = false;
        if ($id) $this->id = $id;
    }

    //Gestion des uploads

    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */

    public $file_domicile;
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */

    public $file_prestations;
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */

    public $file_salaire_1;
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */

    public $file_salaire_2;
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */

    public $file_salaire_3;
    /**
     * @var \Symfony\Component\HttpFoundation\File\UploadedFile
     */
    public $file_impots;

    private $upload_absolute_path;
    private $upload_folder;

    public function setUploadFolder($folder)
    {
        $this->upload_folder = $folder;
    }

    public function setUploadAbsolutePath($absolutePath)
    {
        $this->upload_absolute_path = $absolutePath;
    }

    protected function getUploadDir()
    {
        return $this->upload_folder;
    }

    protected function getUploadRootDir()
    {
        return $this->upload_absolute_path;
    }

    public function getWebPathDomicile()
    {
        return null === $this->path_domicile ? null : $this->getUploadDir().'/'.$this->path_domicile;
    }

    public function getAbsolutePathDomicile()
    {
        return null === $this->path_domicile ? null : $this->getUploadRootDir().'/'.$this->path_domicile;
    }

    public function getWebPathPrestations()
    {
        return null === $this->path_prestations ? null : $this->getUploadDir().'/'.$this->path_prestations;
    }

    public function getAbsolutePathPrestations()
    {
        return null === $this->path_prestations ? null : $this->getUploadRootDir().'/'.$this->path_prestations;
    }
    public function getWebPathSalaire1()
    {
        return null === $this->path_salaire_1 ? null : $this->getUploadDir().'/'.$this->path_salaire_1;
    }

    public function getAbsolutePathSalaire1()
    {
        return null === $this->path_salaire_1 ? null : $this->getUploadRootDir().'/'.$this->path_salaire_1;
    }
    public function getWebPathSalaire2()
    {
        return null === $this->path_salaire_2 ? null : $this->getUploadDir().'/'.$this->path_salaire_2;
    }

    public function getAbsolutePathSalaire2()
    {
        return null === $this->path_salaire_2 ? null : $this->getUploadRootDir().'/'.$this->path_salaire_2;
    }

    public function getWebPathSalaire3()
    {
        return null === $this->path_salaire_3 ? null : $this->getUploadDir().'/'.$this->path_salaire_3;
    }

    public function getAbsolutePathSalaire3()
    {
        return null === $this->path_salaire_3 ? null : $this->getUploadRootDir().'/'.$this->path_salaire_3;
    }

    public function getWebPathImpot()
    {
        return null === $this->path_impots ? null : $this->getUploadDir().'/'.$this->path_impots;
    }

    public function getAbsolutePathImpot()
    {
        return null === $this->path_impots ? null : $this->getUploadRootDir().'/'.$this->path_impots;
    }



    public function preUpload()
    {
        if (null !== $this->file_domicile) {
            // do whatever you want to generate a unique name
            $this->path_domicile = uniqid().'.'.$this->file_domicile->guessExtension();
        }
        if  (null !== $this->file_prestations) {
            // do whatever you want to generate a unique name
            $this->path_prestations = uniqid().'.'.$this->file_prestations->guessExtension();
        }
        if  (null !== $this->file_salaire_1) {
            // do whatever you want to generate a unique name
            $this->path_salaire_1 = uniqid().'.'.$this->file_salaire_1->guessExtension();
        }
        if  (null !== $this->file_salaire_2) {
            // do whatever you want to generate a unique name
            $this->path_salaire_2 = uniqid().'.'.$this->file_salaire_2->guessExtension();
        }
        if  (null !== $this->file_salaire_3) {
            // do whatever you want to generate a unique name
            $this->path_salaire_3 = uniqid().'.'.$this->file_salaire_3->guessExtension();
        }
        if  (null !== $this->file_impots) {
            // do whatever you want to generate a unique name
            $this->path_impots = uniqid().'.'.$this->file_impots->guessExtension();
        }

    }

    public function upload()
    {
        if (!is_null($this->file_domicile)) {
            $this->file_domicile->move($this->getUploadRootDir(), $this->path_domicile);
            unset($this->file_domicile);
        }

        if (!is_null($this->file_prestations)) {
            $this->file_prestations->move($this->getUploadRootDir(), $this->path_prestations);
            unset($this->file_prestations);
        }
        if (!is_null($this->file_salaire_1)) {
            $this->file_salaire_1->move($this->getUploadRootDir(), $this->path_salaire_1);
            unset($this->file_salaire_1);
        }
        if (!is_null($this->file_salaire_2)) {
            $this->file_salaire_2->move($this->getUploadRootDir(), $this->path_salaire_2);
            unset($this->file_salaire_2);
        }
        if (!is_null($this->file_salaire_3)) {
            $this->file_salaire_3->move($this->getUploadRootDir(), $this->path_salaire_3);
            unset($this->file_salaire_3);
        }
        if (!is_null($this->file_impots)) {
            $this->file_impots->move($this->getUploadRootDir(), $this->path_impots);
            unset($this->file_impots);
        }
    }


    public function removeUpload()
    {
        if ($file = $this->getAbsolutePathDomicile()) {
            unlink($file);
        }
        if ($file = $this->getAbsolutePathPrestations()) {
            unlink($file);
        }
        if ($file = $this->getAbsolutePathSalaire1()) {
            unlink($file);
        }
        if ($file = $this->getAbsolutePathSalaire2()) {
            unlink($file);
        }
        if ($file = $this->getAbsolutePathSalaire3()) {
            unlink($file);
        }
        if ($file = $this->getAbsolutePathImpot()) {
            unlink($file);
        }
    }


    /** Generate code */

    /**
     * @var string
     */
    private $adresse;

    /**
     * @var integer
     */
    private $codePostal;

    /**
     * @var string
     */
    private $commune;

    /**
     * @var integer
     */
    private $telephoneSecondaire;

    /**
     * @var string
     */
    private $caf;

    /**
     * @var string
     */
    private $modeDePaiement;

    /**
     * @var string
     */
    private $numeroIban;

    /**
     * @var boolean
     */
    private $mandatActif;

    /**
     * @var boolean
     */
    private $validation;

    /**
     * @var string
     */
    private $path_domicile;

    /**
     * @var string
     */
    private $path_prestations;

    /**
     * @var string
     */
    private $path_salaire_1;

    /**
     * @var string
     */
    private $path_salaire_2;

    /**
     * @var string
     */
    private $path_salaire_3;

    /**
     * @var string
     */
    private $path_impots;

    /**
     * @var \Doctrine\Common\Collections\Collection
     */
    private $eleves;

    /**
     * Set adresse
     *
     * @param string $adresse
     *
     * @return User
     */
    public function setAdresse($adresse)
    {
        $this->adresse = $adresse;

        return $this;
    }

    /**
     * Get adresse
     *
     * @return string
     */
    public function getAdresse()
    {
        return $this->adresse;
    }

    /**
     * Set codePostal
     *
     * @param integer $codePostal
     *
     * @return User
     */
    public function setCodePostal($codePostal)
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    /**
     * Get codePostal
     *
     * @return integer
     */
    public function getCodePostal()
    {
        return $this->codePostal;
    }

    /**
     * Set commune
     *
     * @param string $commune
     *
     * @return User
     */
    public function setCommune($commune)
    {
        $this->commune = $commune;

        return $this;
    }

    /**
     * Get commune
     *
     * @return string
     */
    public function getCommune()
    {
        return $this->commune;
    }

    /**
     * Set telephoneSecondaire
     *
     * @param integer $telephoneSecondaire
     *
     * @return User
     */
    public function setTelephoneSecondaire($telephoneSecondaire)
    {
        $this->telephoneSecondaire = $telephoneSecondaire;

        return $this;
    }

    /**
     * Get telephoneSecondaire
     *
     * @return integer
     */
    public function getTelephoneSecondaire()
    {
        return $this->telephoneSecondaire;
    }

    /**
     * Set caf
     *
     * @param string $caf
     *
     * @return User
     */
    public function setCaf($caf)
    {
        $this->caf = $caf;

        return $this;
    }

    /**
     * Get caf
     *
     * @return string
     */
    public function getCaf()
    {
        return $this->caf;
    }

    /**
     * Set modeDePaiement
     *
     * @param string $modeDePaiement
     *
     * @return User
     */
    public function setModeDePaiement($modeDePaiement)
    {
        $this->modeDePaiement = $modeDePaiement;

        return $this;
    }

    /**
     * Get modeDePaiement
     *
     * @return string
     */
    public function getModeDePaiement()
    {
        return $this->modeDePaiement;
    }

    /**
     * Set numeroIban
     *
     * @param string $numeroIban
     *
     * @return User
     */
    public function setNumeroIban($numeroIban)
    {
        $this->numeroIban = $numeroIban;

        return $this;
    }

    /**
     * Get numeroIban
     *
     * @return string
     */
    public function getNumeroIban()
    {
        return $this->numeroIban;
    }

    /**
     * Set mandatActif
     *
     * @param boolean $mandatActif
     *
     * @return User
     */
    public function setMandatActif($mandatActif)
    {
        $this->mandatActif = $mandatActif;

        return $this;
    }

    /**
     * Get mandatActif
     *
     * @return boolean
     */
    public function getMandatActif()
    {
        return $this->mandatActif;
    }

    /**
     * Set validation
     *
     * @param boolean $validation
     *
     * @return User
     */
    public function setValidation($validation)
    {
        $this->validation = $validation;

        return $this;
    }

    /**
     * Get validation
     *
     * @return boolean
     */
    public function getValidation()
    {
        return $this->validation;
    }

    /**
     * Set pathDomicile
     *
     * @param string $pathDomicile
     *
     * @return User
     */
    public function setPathDomicile($pathDomicile)
    {
        $this->path_domicile = $pathDomicile;

        return $this;
    }

    /**
     * Get pathDomicile
     *
     * @return string
     */
    public function getPathDomicile()
    {
        return $this->path_domicile;
    }

    /**
     * Set pathPrestations
     *
     * @param string $pathPrestations
     *
     * @return User
     */
    public function setPathPrestations($pathPrestations)
    {
        $this->path_prestations = $pathPrestations;

        return $this;
    }

    /**
     * Get pathPrestations
     *
     * @return string
     */
    public function getPathPrestations()
    {
        return $this->path_prestations;
    }

    /**
     * Set pathSalaire1
     *
     * @param string $pathSalaire1
     *
     * @return User
     */
    public function setPathSalaire1($pathSalaire1)
    {
        $this->path_salaire_1 = $pathSalaire1;

        return $this;
    }

    /**
     * Get pathSalaire1
     *
     * @return string
     */
    public function getPathSalaire1()
    {
        return $this->path_salaire_1;
    }

    /**
     * Set pathSalaire2
     *
     * @param string $pathSalaire2
     *
     * @return User
     */
    public function setPathSalaire2($pathSalaire2)
    {
        $this->path_salaire_2 = $pathSalaire2;

        return $this;
    }

    /**
     * Get pathSalaire2
     *
     * @return string
     */
    public function getPathSalaire2()
    {
        return $this->path_salaire_2;
    }

    /**
     * Set pathSalaire3
     *
     * @param string $pathSalaire3
     *
     * @return User
     */
    public function setPathSalaire3($pathSalaire3)
    {
        $this->path_salaire_3 = $pathSalaire3;

        return $this;
    }

    /**
     * Get pathSalaire3
     *
     * @return string
     */
    public function getPathSalaire3()
    {
        return $this->path_salaire_3;
    }

    /**
     * Set pathImpots
     *
     * @param string $pathImpots
     *
     * @return User
     */
    public function setPathImpots($pathImpots)
    {
        $this->path_impots = $pathImpots;

        return $this;
    }

    /**
     * Get pathImpots
     *
     * @return string
     */
    public function getPathImpots()
    {
        return $this->path_impots;
    }

    /**
     * Add elefe
     *
     * @param \WCS\CantineBundle\Entity\Eleve $elefe
     *
     * @return User
     */
    public function addElefe($elefe)
    {
        $this->eleves[] = $elefe;

        return $this;
    }

    /**
     * Remove elefe
     *
     * @param \WCS\CantineBundle\Entity\Eleve $elefe
     */
    public function removeElefe($elefe)
    {
        $this->eleves->removeElement($elefe);
    }

    /**
     * Get eleves
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getEleves()
    {
        return $this->eleves;
    }
}
